version: "3.8"
services:
  online_shop:
    image: sumit2703/online-shop:latest  
    container_name: online_shop
    ports:
      - "3000:80"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"] 
      interval: 60s
      timeout: 10s
      retries: 5
    networks:
      - online_shop

networks:
  online_shop:
    driver: bridge
