apiVersion: v1
kind: Service
metadata:
  name: online-shop-service
  namespace: online-shop
spec:
  type: NodePort
  selector:
    app: online-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30080
