# .github/workflows/cicd.yml
name: CI/CD Pipeline

on:
  push:
    branches: main

env:
  DOCKER_IMAGE: sumit2703/online-shop

jobs:
  build-and-push:
    runs-on: [self-hosted, kind, local]    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

  deploy-to-kind:
    needs: build-and-push
    runs-on: [self-hosted, kind, local]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set kubeconfig for Kind
        run: |
          kind export kubeconfig --name kind

      - name: Deploy to Kubernetes
        run: |
          # Namespace
          kubectl apply -f k8s/namespace.yml
          
          # Deployment + Service
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml

          # Update deployment image
          kubectl set image deployment/online-shop online-shop=${{ env.DOCKER_IMAGE }}:${{ github.sha }} -n online-shop
          
          # HPA
          kubectl apply -f k8s/hpa.yml
          
          # Ingress / Gateway for external access
          kubectl apply -f k8s/ingress.yml
          
          # Rollout status
          kubectl rollout status deployment/online-shop -n online-shop

      - name: Verify
        run: |
          kubectl get pods -n online-shop
          kubectl get svc -n online-shop
          kubectl get hpa -n online-shop
          kubectl get ingress -n online-shop
